// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthUserCreate struct {
	FirstName string `json:"FirstName"`
	LastName  string `json:"LastName"`
	Email     string `json:"Email"`
	Password  string `json:"Password"`
}

type AuthUserResponse struct {
	ID          *string `json:"Id,omitempty"`
	FirstName   string  `json:"FirstName"`
	LastName    string  `json:"LastName"`
	Email       string  `json:"Email"`
	TimeCreated string  `json:"TimeCreated"`
	TimeUpdated string  `json:"TimeUpdated"`
}

type Mutation struct {
}

type Query struct {
}
