// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthUser struct {
	ID        int32  `json:"id"`
	Username  string `json:"username"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type AuthUserCreate struct {
	Username  string `json:"username"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type AuthUserLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AuthUserResponse struct {
	AuthUser *AuthUser `json:"authUser"`
	Token    string    `json:"token"`
}

type Filters struct {
	Skip  int32 `json:"skip"`
	Limit int32 `json:"limit"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type MessageInput struct {
	SenderID   string `json:"sender_id"`
	ReceiverID int32  `json:"receiver_id"`
	Content    string `json:"content"`
}

type MessageResponse struct {
	ID         int32  `json:"id"`
	SenderID   int32  `json:"sender_id"`
	ReceiverID int32  `json:"receiver_id"`
	Content    string `json:"content"`
	CreatedAt  string `json:"createdAt"`
}

type MessageSub struct {
	Receiver int32 `json:"receiver"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type Time struct {
	UnixTime  int32  `json:"unixTime"`
	TimeStamp string `json:"timeStamp"`
}

type UserEmail struct {
	Email string `json:"email"`
}
